### ISSUE TITLE
No Update of the Page?

### ISSUE THREAD

**Issue by puzich** [Niek/tesla-superchargers#11]
Hi there, 

the page wasn't updated since month. Is there an issue?

Best regards
Thorsten

**Comment by Niek** [comment]
> Error calling API: Response code 403 (Forbidden)

Seems like there was an update again, blocking the API calls. They make it extremely hard to scrape pricing info, unfortunately :(

**Comment by puzich** [comment]
That is sad. Will you fix it? Or could you give me a hit how to find the new API calls?

**Comment by tomkiss** [comment]
Hey @Niek 

If you remove the user-agent from the outgoing request, this should start working again. [PR here](https://github.com/Niek/tesla-superchargers/pull/12).

**Comment by Niek** [comment]
Nice catch! PR merged and prices are updated again. Thanks @tomkiss
