### ISSUE TITLE
No price updates

### ISSUE THREAD

**Issue by 3sRykaert** [Niek/tesla-superchargers#14]
It seems that after this commit, the prices do not appear anymore:
https://github.com/Niek/tesla-superchargers/commit/e316732a06f1db739428d222c2195be738d49dff

**Comment by Niek** [comment]
I see `Error calling API: Response code 403 (Forbidden)` returned from the API calls, I'm afraid the `https://akamai-apigateway-charging-ownership.tesla.com/graphql` API is no longer working or requires some special headers.

@tomkiss do you have any idea?

**Comment by tomkiss** [comment]
No, same problem here I'm afraid.

**Comment by Niek** [comment]
Fixed with a24499630b24458390d149da8af40b247be79fce (for now, at least)

**Comment by 3sRykaert** [comment]
> Fixed with [a244996](https://github.com/Niek/tesla-superchargers/commit/a24499630b24458390d149da8af40b247be79fce) (for now, at least)

@Niek 'it happened again' no prices shown anymore.
I guess it's a "game of mouse and cat" :-)

**Comment by Niek** [comment]
> > Fixed with [a244996](https://github.com/Niek/tesla-superchargers/commit/a24499630b24458390d149da8af40b247be79fce) (for now, at least)
> 
> @Niek 'it happened again' no prices shown anymore. I guess it's a "game of mouse and cat" :-)

You are right, this time the API call is returned without error, but the `sitePricing` object is empty... Not really sure if the API changed or if it's some other issue. Maybe someone with RE/SSL interception skills can check the endpoint calls?
