### ISSUE TITLE
Prices for Tesla owners

### ISSUE THREAD

**Issue by marki555** [Niek/tesla-superchargers#9]
Now that you can view SuC prices in the app (when you click on Location, you can find SuC on map, or when starting navigation from the app), is it possible to get the prices also here? Is some reverse-engineering of the app code needed to find out the URLs?

**Comment by marki555** [comment]
I have found this page https://chargeinsights.com/tesla-supercharger-price-analysis-europe/ which shows the prices on the map (needs zooming for the prices to appear under the dots).

**Comment by Niek** [comment]
This is already in the page - it's called "pricing members"

**Comment by marki555** [comment]
Yes, but still only for those SuC which are open to non-Teslas, so Slovakia is still missing. I can view the SuC prices in tesla app. But maybe in the Location map in app it is using different API?

**Comment by Niek** [comment]
Yes, this API can *only* request pricing for SuCs that re open to non-Teslas. Unless someone finds a GraphQL call to get pricing for all SuCs, I'm afraid there is no workaround.

**Comment by marki555** [comment]
Someone already did find it, but seems they don't publish the details.
https://chargeinsights.com/tesla-supercharger-price-analysis-europe/ 
But Slovakia SuCs are in their map.
